### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [nfdz/Cryptool#51]
First up, great to see another release of this fine app! When pulling it in however the scanners here at IzzyOnDroid sounded a little warning:

```
! repo/io.github.nfdz.cryptool_20.apk declares sensitive permission(s):
  android.permission.SYSTEM_ALERT_WINDOW android.permission.SEND_SMS
  android.permission.RECEIVE_SMS android.permission.READ_SMS
! repo/io.github.nfdz.cryptool_20.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

The SMS permissions are rather clear, and Ive added them to the app's "green list" right away:

```yaml
    android.permission.SEND_SMS: required by the SMS provider
    android.permission.RECEIVE_SMS: required by the SMS provider
    android.permission.READ_SMS: required by the SMS provider
```

But could you please (confirm this and) clarify about the missing one (`SYSTEM_ALERT_WINDOW`)?

As for `DEPENDENCY_INFO_BLOCK`, that can be avoided easily with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!
